version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: price-aggregator-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: price-aggregator
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:7-alpine
    container_name: price-aggregator-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: price-aggregator-api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/price-aggregator
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_KEY=${API_KEY:-test-api-key-1234}
      - PORT=3000
      - FETCH_INTERVAL=10000
      - STALENESS_THRESHOLD=60000

volumes:
  postgres-data:
  redis-data: 